package com.mingpinmall.me.ui.constants;

/**
 * 常量
 */
public interface Constants {

    /*UserViewModel*/
    Object RESET_PASSWORD = "RESET_PASSWORD";
    Object LOGIN = "USER_INFO";
    Object CHECK_CODE = "CHECK_CODE";
    Object CHECK_PAY_PASSWORD = "CHECK_PAY_PASSWORD";
    Object GET_SMS_CODE = "GET_SMS_CODE";
    Object BIND_PHONE = "BIND_PHONE";

    /*MeViewModel*/
    Object UPLOAD_FILES = "UPLOAD_FILES";
    Object POST_REFUND = "POST_REFUND";
    Object POST_REFUND_ALL = "POST_REFUND_ALL";
    Object REFUND_SHOPS_INFO = "REFUND_SHOPS_INFO";
    Object REFUND_ORDER_INFO = "REFUND_ORDER_INFO";
    Object SEND_EVALUATE = "SEND_EVALUATE";
    Object ORDER_EVALUATE_LIST = "ORDER_EVALUATE_LIST";
    Object ADD_PDCASH = "ADD_PDCASH";
    Object BIND_USER_CODE = "BIND_USER_CODE";
    Object REDUCE_CASH = "REDUCE_CASH";
    Object MESSAGE_LIST = "MESSAGE_LIST";
    Object DELETE_MESSAGE = "DELETE_MESSAGE";
    Object RETURN_INFORMATION = "RETURN_INFORMATION";
    Object REFUND_INFORMATION = "REFUND_INFORMATION";
    Object VIP_POINT = "VIP_POINT";
    Object VIP_POINT_LOG = "VIP_POINT_LOG";
    Object PACKET_LIST = "PACKET_LIST";
    Object COUPON_CHARGE = "COUPON_CHARGE";
    Object RCARD_CHARGE = "RCARD_CHARGE";
    Object PACKET_CHARGE = "PACKET_CHARGE";
    Object RCCHARGE_LIST = "RCCHARGE_LIST";
    Object RCBALANCE = "RCBALANCE";
    Object COUPONLISTBEAN = "COUPONLISTBEAN";
    Object PREDEPOIT = "PREDEPOIT";
    Object PREDPOSITLOG = "PREDPOSITLOG";
    Object PDRECHARGE = "PDRECHARGE";
    Object PDCASH = "PDCASH";
    Object PDCASH_INFORMATION = "PDCASH_INFORMATION";
    Object REFUND = "REFUND";
    Object RETURN = "RETURN";
    Object VIRTUAL_ORDER_INFORMATION = "VIRTUAL_ORDER_INFORMATION";
    Object VIRTUAL_ORDER_ADDRS = "VIRTUAL_ORDER_ADDRS";
    String RECEVIE_ORDER = "RECEVIE_ORDER";
    String REMOVE_ORDER = "REMOVE_ORDER";
    Object DEL_ADDRESS = "DEL_ADDRESS";
    Object ADDRESS_LIST = "ADDRESS_LIST";
    Object EDIT_ADDRESS = "EDIT_ADDRESS";
    Object CITY_LIST = "CITY_LIST";
    Object CLEAR_FOOTPRINT = "CLEAR_FOOTPRINT";
    Object GET_FOOTPRINT = "GET_FOOTPRINT";
    Object GET_USER_INFO = "GET_USER_INFO";
    Object USER_PAYPWD_INFO = "USER_PAYPWD_INFO";
    Object USER_PHONE_INFO = "USER_PHONE_INFO";
    Object Err_USER_INFO = "Err_USER_INFO";
    Object MY_ASSET = "MY_ASSET";
    Object SEND_FEEDBACK = "SEND_FEEDBACK";
    Object SHOPS_COLLECT_LIST = "SHOPS_COLLECT_LIST";
    Object DEL_SHOP_COLLECT = "DEL_SHOP_COLLECT";
    Object DEL_GOODS_COLLECT = "DEL_GOODS_COLLECT";
    Object PRODUCT_COLLECT_LIST = "PRODUCT_COLLECT_LIST";
    Object PHYSICAL_ORDER_INFORMATION = "PHYSICAL_ORDER_INFORMATION";
    Object ORDER_DELIVER_INFORMATION = "ORDER_DELIVER_INFORMATION";
    Object ORDER_DELIVER_LIST = "ORDER_DELIVER_LIST";
}
