package com.mingpinmall.classz.constants;

/**
 * 常量
 */
public interface Constants {

    /*左边*/
    Object EVENT_KEY_CLASSIFY_MORE = "EVENT_KEY_CLASSIFY_MORE";
    Object EVENT_KEY_CLASSIFY_MORE_STATE = "EVENT_KEY_CLASSIFY_MORE_STATE";

    /*右边*/
    Object EVENT_KEY_CLASSIFY_MORE_RIGHT = "EVENT_KEY_CLASSIFY_MORE_RIGHT";
//    Object EVENT_KEY_CLASSIFY_KEY_MORE_STATE = "EVENT_KEY_CLASSIFY_KEY_MORE_STATE";

    /*左边的index*/
//    String POSTION_LEF_EVENT_KEY = "POSTION_LEF_EVENT_KEY";
//    String POSTION_LEF_EVENT_KEY_TAG = "POSTION_LEF_EVENT_KEY_TAG";

    /*商品分类*/
    String[] PRODUCTS_TITLE = {"综合排序", "销量优先", "筛选"};
    Object PRODUCTS_EVENT_KEY = "PRODUCTS_EVENT_KEY";
    Object PRODUCTS_EVENT_KEY_TAG = "PRODUCTS_EVENT_KEY_TAG";
    Object PRODUCTS_EVENT_KEY_LIST_STATE = "PRODUCTS_EVENT_KEY_LIST_STATE";

    /*商品详情*/
    Object GOODSDETAIL_EVENT_KEY = "GOODSDETAIL_EVENT_KEY";
    /*购物车KEY*/
    Object CART_EVENT_KEY = "CART_EVENT_KEY";

    Object GOODSDETAIL_EVENT_KEY_STATE = "GOODSDETAIL_EVENT_KEY_STATE";

    /*收藏*/
    Object FAVORITES = "FAVORITES";

    String PAGE_RN = "10";


    /*评价列表*/
    Object EVALUATE_EVENT_KEY_LIST_STATE = "EVALUATE_EVENT_KEY_LIST_STATE";
    Object EVALUATE_EVENT_KEY = "EVALUATE_EVENT_KEY";
}
